name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} -t ghcr.io/promisenwafor/simplebiz:latest .
          docker push ghcr.io/promisenwafor/simplebiz:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ghcr.io/promisenwafor/simplebiz:latest
            docker stop simplebiz || true
            docker rm simplebiz || true
            docker run -d --name simplebiz -p 3000:3000 ghcr.io/promisenwafor/simplebiz:latest
